language: node_js
node_js:
 - "12"
sudo : true
branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - nvm alias default 12
  - nvm use 12
  - npm install @angular/cli -g
  - npm install -g @ionic/cli

cache:
  yarn: true
  directories:
    - node_modules

script :
  - ionic build --prod --aot
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID_AWS
  secret_access_key: $SECRET_ACCESS_KEY_AWS
  bucket : "ppt-t2s"
  #  The clean up is skipped so that the jar file would not b e removed
  skip_cleanup: true
  local_dir: ./www/
  acl: public_read